site_name: DAOstack Developer Egress
repo_url: https://github.com/daostack/DAOstack-Hacker-Kit/
repo_name: daostack/DAOstack-Hacker-Kit
site_description: A platform for building DAOs
docs_dir: docs
markdown_extensions:
- admonition
- codehilite:
    linenums: true
- toc:
    permalink: true
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'pink'
  logo: 'images/daostack-logoW.svg'

extra:
  social:
  - type: 'github'
    link: 'https://github.com/daostack/DAOstack-Hacker-Kit'
  - type: 'slack'
    link: 'https://daostack.slack.com'
  - type: 'telegram'
    link: 'https://t.me/daostackcommunity'

nav:
- Home: 'index.md'
- Stack:
  - Infra: 'stack/infra/infraIntro.md'
  - Arc: 'stack/arc/arcIntro.md'
  - Client:
    - Intro: 'stack/client/clientIntro.md'
    - Client: 'stack/client/clientApi.md'
  - Subgraph:
    - Intro: 'stack/subgraph/subgraphIntro.md'
    - GraphQL queries: 'stack/subgraph/queries.md'
    - Entities: 'stack/subgraph/entities.md'
  - DApps/Alchemy: 'stack/alchemy/alchemyIntro.md'
- Migration: 'migration.md'
- Tutorials:
    - Add features to Alchemy interface: 'gettingStarted/setupAlchemyDevMode.md'
    - Setup Generic Scheme for a DAO: 'gettingStarted/setupGenericScheme.md'
    - Add custom scheme to the DAO:
      - Intro: 'gettingStarted/customScheme/intro.md'
      - Arc:
        - 'Non-Universal Scheme': 'gettingStarted/customScheme/developCustomNonUniScheme.md'
        - 'Universal Scheme': 'gettingStarted/customScheme/developCustomUniScheme.md'
      - Migration:
        - Register scheme to new DAO: 'gettingStarted/customScheme/registerToNewDAO.md'
        - Register scheme to existing DAO: 'gettingStarted/customScheme/registerToExistingDAO.md'
      - 'Subgraph: enable cache for new scheme': 'gettingStarted/customScheme/subgraphForNewScheme.md'
      - 'Client: interact with new Scheme': 'gettingStarted/customScheme/clientForNewScheme.md'
      - 'Alchemy: integrate with DAOstack interface': 'gettingStarted/customScheme/alchemyIntegrationForNewScheme.md'
    - Deploy a DAO: 'gettingStarted/deployDAO.md'
    - Create your own interface for DAOstack DAOs: 'gettingStarted/createNewInterface.md'
- Hacker-kit: 'hackerkit.md'
- Want to contribute?:
    - Feature Requests: 'feature-requests.md'
    - Propose to Genesis DAO: 'how-to-propose.md'
